# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d13402bb207fa4d5128c731dcbec666395a796370d80826866022070481db5e579b928884230db59398bf63c8794d4448ad2ca73c8c6a6485a1165310d03c4f

test:
  secret_key_base: 2b112a4a39c3ecd9e427174f12b3f2abce64ad737c21f01ee401b6463b09e3b2c65e44d3281d638305c6ee4a3de50cf41c65b300e9daa9e02667b1362a0cb537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
