User.create!([
  {username: nil, postal: nil, points: 102, email: "glendonyeo@gmail.com", encrypted_password: "$2a$10$qAG1D/regi/IA9dY/R4D1Oo9hJOxlYnTo27WsPVfgDt0946IJ3PU2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-01-13 13:46:42", last_sign_in_at: "2016-01-13 13:46:42", current_sign_in_ip: "::1", last_sign_in_ip: "::1", provider: nil, uid: nil},
  {username: nil, postal: nil, points: 96, email: "jinwen@gmail.com", encrypted_password: "$2a$10$P/dXvFHGE5j80QtDKw1HN.L1QSUglzX5o3mqQCPNJa0TNGTve7nw.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-01-14 16:52:05", last_sign_in_at: "2016-01-14 11:59:16", current_sign_in_ip: "::1", last_sign_in_ip: "::1", provider: nil, uid: nil}
])
Book.create!([
  {name: "DITA Best Practices", price: 1, categories: "Non-Textbooks", condition: "OK", description: "The complete, best-practice guide to implementing and using DITA: expert, 'in the trenches' advice you can't find anywhere else! • •Answers the crucial questions the 'official' DITA documentation doesn't cover, from 'Where do you start?' to 'How do you avoid the pitfalls?' •Reflects the authors' unsurpassed experience in all facets of enterprise-scale DITA planning, deployment, and day-to-day usage. •Offers practical guidance on topic-based writing, content architecture, and ensuring a quality implementation. Darwin Information Typing Architecture (DITA) is today's most powerful toolbox for constructing information. Implementing DITA can help organizations significantly improve the value of their technical documentation. This book brings together best practices and real-world guidance for success with DITA deployment and usage. Drawing on years of experience helping organizations implement DITA, the authors answer the crucial questions the 'official' DITA documents ignore: • •Where do you start in implementing DITA? •What should you know before you start writing? •What are DITA's gotchas and pitfalls? •Which DITA elements, attributes, and features should you know upfront, and which can wait? Technical writers and their managers can use this book as a complete roadmap for DITA adoption and implementation. Part 1 walks through the basics of topic-based writing, especially the importance of writing accurate, usable short descriptions. Part 2 covers more advanced topics related to content architecture, including DITA maps, linking strategies, metadata, conditional processing, and content reuse. Part 3 covers quality DITA implementations, offering crucial guidance for converting content to DITA, whether you do it in-house or utilize a third-party vendor.", prefered_location: "Sdfasdf", user_id: 1, isbn: "9780132480529", image_url: "http://books.google.com.my/books/content?id=0jKRrpKJ9CsC&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", subtitle: "A Roadmap for Writing, Editing, and Architecting in DITA", big_image: "http://books.google.com.my/books/content?id=0jKRrpKJ9CsC&printsec=frontcover&img=1&zoom=2&edge=none&source=gbs_api", author: "Laura Bellamy, Michelle Carey, Jenifer Schlotfeldt", published_date: "2011-09-01", pages: 281, language: "en", country: nil, rating_average: 2.0, rating_count: 1, publisher: "IBM Press", preview_link: "http://books.google.com.my/books?id=0jKRrpKJ9CsC&printsec=frontcover&dq=isbn:+9780132480529&hl=&cd=1&source=gbs_api", section: "Computers"},
  {name: "IELTS", price: 1, categories: "University Textbooks", condition: "Looks bad", description: "The Complete Guide to Task 1 Writing has been written for both beginners and more advanced students of IELTS and offers an ideal way to prepare more thoroughly for the IELTS test. The student is taken step by step in simple, plain English through all the various stages of writing a 150-word Task 1 essay. The mistakes commonly made when analysing a diagram are highlighted and more effective, easy to remember, tips are provided to help ensure a higher grade in the exam. Diagrams include: bar charts, line charts, pie charts, tables, processes, cycles, flow charts, objects and maps. Model answers are provided for each diagram and help explain more clearly what the IELTS examiner is looking for when marking the Task 1 essay.", prefered_location: "dfas", user_id: 1, isbn: "9780956633200", image_url: "http://books.google.com.my/books/content?id=cTPecQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subtitle: "The Complete Guide to Task 1 Writing with Answers and Model Essays", big_image: "http://books.google.com.my/books/content?id=cTPecQAACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api", author: "Phil Biggerton", published_date: nil, pages: 139, language: "en", country: nil, rating_average: 5.0, rating_count: 2, publisher: nil, preview_link: "http://books.google.com.my/books?id=cTPecQAACAAJ&dq=isbn:+9780956633200&hl=&cd=1&source=gbs_api", section: "Education"},
  {name: "Book Love", price: 1, categories: "University Textbooks", condition: "Looks bad", description: "Presents strategies for getting students to read, and offers advice on building a school culture around a love of reading, helping students deepen their understanding of what they read, and balancing independent reading and text study.", prefered_location: "asdf", user_id: 1, isbn: "9780325042954", image_url: "http://books.google.com.my/books/content?id=wK01LgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subtitle: "Developing Depth, Stamina, and Passion in Adolescent Readers", big_image: "http://books.google.com.my/books/content?id=wK01LgEACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api", author: "Penny Kittle", published_date: "2012-10-26", pages: 174, language: "en", country: nil, rating_average: 4.5, rating_count: 47, publisher: "Heinemann Educational Books", preview_link: "http://books.google.com.my/books?id=wK01LgEACAAJ&dq=isbn:+9780325042954&hl=&cd=1&source=gbs_api", section: "Education"},
  {name: "Chinese History", price: 2, categories: "Secondary School Textbooks", condition: "OK", description: "Since publication of the first edition in 1998, Chinese History: A Manual has become an indispensable guide to researching the civilization and history of China. Updated through January 2000, the second edition discusses some 4,300 primary, secondary, and reference works, an increase of 1,500 titles over the first edition. The temporal coverage has been expanded to include the Republican period; sections on nonverbal salutations, weights and measures, money, and furniture have been added; the chapters on language, etymology, people, geography, chronology, warfare, leishu, food, and the Chinese world order have been thoroughly revised; and the subject index has been enlarged to include 2,500 technical terms.", prefered_location: "123", user_id: 1, isbn: "9780674002494", image_url: "http://books.google.com.my/books/content?id=ERnrQq0bsPYC&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", subtitle: "A Manual", big_image: "http://books.google.com.my/books/content?id=ERnrQq0bsPYC&printsec=frontcover&img=1&zoom=2&edge=none&source=gbs_api", author: "Endymion Porter Wilkinson", published_date: nil, pages: 1181, language: "en", country: nil, rating_average: 4.5, rating_count: 6, publisher: "Harvard Univ Asia Center", preview_link: "http://books.google.com.my/books?id=ERnrQq0bsPYC&pg=PA495&dq=isbn:+9780674002494&hl=&cd=1&source=gbs_api", section: "History"}
])
BookTransaction.create!([
  {status: "successful", user_id: 2, book_id: 1},
  {status: "successful", user_id: 2, book_id: 2},
  {status: "pending", user_id: 2, book_id: 4}
])
